import { cloneElement, useEffect, useState, type FormEvent, type ReactElement } from "react";
import { BadgeCheck, Edit2, Eye, EyeOff, Loader2, Plus, RefreshCw, Search, Trash2, UserRound, X } from "lucide-react";
import CreatorEditableFields, { emptyEditableProfile } from "../creator-network/CreatorEditableFields";
import { createCreator, creatorError, deleteCreator, fetchAdminCreator, fetchAdminCreators, updateCreator, type CreatorFilters, type CreatorInput, type CreatorRecord } from "../../services/creatorStore";

const empty = (): CreatorInput => ({ ...emptyEditableProfile(), full_name: "", slug: "", brand_love_heading: null, followers_override: null, engagement_rate: 0, compatibility_score: null, is_verified: false, status: "hidden", display_order: 0 });
const fromRecord = (c: CreatorRecord): CreatorInput => ({ full_name: c.full_name || "", display_name: c.display_name, email: c.email || "", whatsapp: c.whatsapp || null, slug: c.slug, profile_image_url: c.profile_image_url, portfolio_url: c.portfolio_url, short_bio: c.short_bio, about: c.about, brand_love_heading: c.brand_love_heading ?? null, city: c.city, region: c.region, followers_override: c.followers_override ?? null, engagement_rate: c.engagement_rate, compatibility_score: c.compatibility_score, is_verified: c.is_verified, status: c.status, display_order: c.display_order, socials: c.socials.length ? c.socials : emptyEditableProfile().socials, categories: c.categories.length ? c.categories : [""], expertise: c.expertise.length ? c.expertise : [""], collaboration_types: c.collaboration_types.length ? c.collaboration_types : [""], featured_work: c.featured_work, brand_love_points: c.brand_love_points ?? [] });
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export default function CreatorsAdmin() {
  const [creators, setCreators] = useState<CreatorRecord[]>([]); const [form, setForm] = useState<CreatorInput>(empty); const [editingId, setEditingId] = useState<string | null>(null); const [filters, setFilters] = useState<CreatorFilters>({ status: "", search: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setCreators(await fetchAdminCreators(filters)); } catch (failure) { setError(creatorError(failure)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const edit = async (id: string) => { setSaving(true); setError(""); try { const creator = await fetchAdminCreator(id); setForm(fromRecord(creator)); setEditingId(id); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (failure) { setError(creatorError(failure)); } finally { setSaving(false); } };
  const reset = () => { setForm(empty()); setEditingId(null); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setError(""); setSuccess(""); const payload = { ...form, slug: form.slug || slugify(form.display_name), categories: form.categories.map((x) => x.trim()).filter(Boolean), expertise: form.expertise.map((x) => x.trim()).filter(Boolean), collaboration_types: form.collaboration_types.map((x) => x.trim()).filter(Boolean), socials: form.socials.filter((x) => x.platform.trim() && x.profile_url.trim()), featured_work: form.featured_work.filter((x) => x.title.trim() && x.work_url.trim()) }; try { const saved = editingId ? await updateCreator(editingId, payload) : await createCreator(payload); setCreators((current) => editingId ? current.map((c) => c.id === editingId ? saved : c) : [...current, saved]); setSuccess(`${saved.display_name} was saved successfully.`); reset(); } catch (failure) { setError(creatorError(failure)); } finally { setSaving(false); } };
  const remove = async (creator: CreatorRecord) => { if (!confirm(`Delete “${creator.display_name}”? All Creator-owned socials, categories, expertise, collaboration types, featured work, and access tokens will also be removed. This cannot be undone.`)) return; setSaving(true); try { await deleteCreator(creator.id); setCreators((current) => current.filter((c) => c.id !== creator.id)); setSuccess(`${creator.display_name} was deleted.`); } catch (failure) { setError(creatorError(failure)); } finally { setSaving(false); } };
  const toggle = async (creator: CreatorRecord) => { setSaving(true); try { const updated = await updateCreator(creator.id, { ...fromRecord(creator), status: creator.status === "published" ? "hidden" : "published" }); setCreators((current) => current.map((c) => c.id === creator.id ? updated : c)); } catch (failure) { setError(creatorError(failure)); } finally { setSaving(false); } };
  const setControlled = <K extends keyof CreatorInput>(key: K, value: CreatorInput[K]) => setForm((current) => ({ ...current, [key]: value }));

  return <div className="space-y-8"><form onSubmit={submit} className="space-y-6"><div className="rounded-2xl bg-[#0B241F] p-6 text-white"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-300">Creator Network CMS</p><h1 className="mt-2 text-2xl font-bold text-white">{editingId ? "Edit Creator" : "Add Creator"}</h1><p className="mt-2 text-sm text-white/65">Manage the complete final Creator profile schema.</p></div>{editingId && <button type="button" onClick={reset} className="rounded-xl border border-white/20 p-3"><X /></button>}</div></div>
    <CreatorEditableFields value={form} onChange={setForm} showFullName uploadMode="admin" />
    <section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="font-heading text-lg font-bold">Admin-Controlled Profile Settings</h2><p className="mt-1 text-xs text-gray-500">Calculated followers come from social account counts. Only use an override for a deliberate correction.</p><div className="mt-5 max-w-2xl"><Control label="Why Brands Love Section Heading"><input value={form.brand_love_heading ?? ""} onChange={(e) => setControlled("brand_love_heading", e.target.value || null)} placeholder={`Why Brands Love Working With ${form.display_name || "This Creator"}`} /></Control><p className="mt-1 text-xs text-gray-500">Displayed exactly as entered when brand-love cards are present.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Control label="Slug"><input required value={form.slug} onChange={(e) => setControlled("slug", e.target.value)} placeholder="creator-name" /></Control><Control label="Follower Override"><input type="number" min="0" value={form.followers_override ?? ""} onChange={(e) => setControlled("followers_override", e.target.value === "" ? null : Number(e.target.value))} placeholder="Leave blank" /></Control><Control label="Engagement Rate %"><input type="number" min="0" max="100" step="0.01" value={form.engagement_rate} onChange={(e) => setControlled("engagement_rate", Number(e.target.value))} /></Control><Control label="Compatibility Score"><input type="number" min="0" max="100" value={form.compatibility_score ?? ""} onChange={(e) => setControlled("compatibility_score", e.target.value === "" ? null : Number(e.target.value))} /></Control><Control label="Status"><select value={form.status} onChange={(e) => setControlled("status", e.target.value as CreatorInput["status"])}><option value="hidden">Hidden</option><option value="published">Published</option></select></Control><Control label="Display Order"><input type="number" min="0" value={form.display_order} onChange={(e) => setControlled("display_order", Number(e.target.value))} /></Control><label className="flex items-center gap-2 pt-8 text-sm font-semibold"><input type="checkbox" checked={form.is_verified} onChange={(e) => setControlled("is_verified", e.target.checked)} className="accent-primary" /> Verified Creator</label></div></section>
    {error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{success && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{success}</p>}<button disabled={saving} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-4 font-bold text-white disabled:opacity-60">{saving ? <Loader2 className="animate-spin" /> : <Plus />}{saving ? "Saving..." : editingId ? "Update Creator" : "Create Creator"}</button></form>

    <section className="space-y-5"><div className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-gray-400" size={17} /><input value={filters.search || ""} onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))} placeholder="Search Creators" className="w-full rounded-xl border border-gray-200 py-2.5 pl-10 pr-3" /></label><select value={filters.status || ""} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value as CreatorFilters["status"] }))} className="rounded-xl border border-gray-200 px-4"><option value="">All statuses</option><option value="published">Published</option><option value="hidden">Hidden</option></select><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-secondary px-5 py-2.5 text-sm font-semibold text-white"><RefreshCw size={16} /> Apply</button></div></div>
    {loading ? <p className="py-16 text-center text-gray-500">Loading Creators...</p> : creators.length === 0 ? <div className="rounded-2xl bg-white py-16 text-center text-gray-500">No Creator records found.</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{creators.map((creator) => <article key={creator.id} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex gap-4"><div className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-gray-100">{creator.profile_image_url ? <img src={creator.profile_image_url} alt="" className="h-full w-full object-cover" /> : <UserRound />}</div><div className="min-w-0"><h3 className="flex items-center gap-1 truncate font-bold">{creator.display_name}{creator.is_verified && <BadgeCheck size={15} className="text-primary" />}</h3><p className="text-xs text-gray-500">/{creator.slug}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-[10px] font-bold uppercase ${creator.status === "published" ? "bg-emerald-50 text-emerald-700" : "bg-gray-100"}`}>{creator.status}</span></div></div><div className="mt-4 grid grid-cols-2 border-y py-3 text-center text-xs"><div><strong className="block text-base">{creator.followers_calculated.toLocaleString()}</strong>Calculated</div><div><strong className="block text-base">{creator.followers_override?.toLocaleString() || "—"}</strong>Override</div></div><div className="mt-3 flex justify-end gap-1"><button onClick={() => void toggle(creator)} title="Publish/hide" className="p-2 text-gray-500">{creator.status === "published" ? <EyeOff /> : <Eye />}</button><button onClick={() => void edit(creator.id)} title="Edit" className="p-2 text-primary"><Edit2 /></button><button onClick={() => void remove(creator)} title="Delete" className="p-2 text-red-500"><Trash2 /></button></div></article>)}</div>}</section></div>;
}

function Control({ label, children }: { label: string; children: ReactElement<{ className?: string }> }) { return <label className="text-sm font-semibold text-gray-700">{label}{cloneElement(children, { className: "mt-2 w-full rounded-xl border border-gray-200 px-3 py-3 outline-none focus:border-primary" })}</label>; }
