import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, BarChart3, Check, ExternalLink, Loader2, MapPin, MessageCircle, Users, X } from "lucide-react";
import { Link, Navigate, useParams } from "react-router-dom";
import { creatorError, fetchPublicCreator, fetchPublicCreators, submitCollaborationRequest, type CollaborationRequestInput, type CreatorRecord } from "../services/creatorStore";
import { getDemoCreators } from "../services/creatorDemoAdapter";
import { CREATOR_FALLBACK_IMAGE, getCreatorWorkThumbnail } from "../utils/creatorThumbnails";
import { creatorBrandIcon } from "../utils/creatorBrandIcons";
const formatCount=(n:number)=>n>=1e6?`${(n/1e6).toFixed(1).replace('.0','')}M`:n>=1e3?`${Math.round(n/1e3)}K`:String(n);
const safeUrl=(v:string|null)=>{if(!v)return null;try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?v:null}catch{return null}};

export default function CreatorDetail(){
 const{id=""}=useParams();const[creator,setCreator]=useState<CreatorRecord|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notFound,setNotFound]=useState(false);const[collaborate,setCollaborate]=useState(false);
 const load=async()=>{setLoading(true);setError("");setNotFound(false);try{setCreator(await fetchPublicCreator(id));}catch(failure){try{const real=await fetchPublicCreators();if(real.length===0){const demo=getDemoCreators().find(x=>x.id===id);demo?setCreator(demo):setNotFound(true);}else setNotFound(true);}catch{setError(creatorError(failure));}}finally{setLoading(false)}};
 useEffect(()=>{void load()},[id]);
 if(loading)return <main className="grid min-h-screen place-items-center pt-24"><Loader2 className="animate-spin text-primary"/></main>;
 if(notFound)return <Navigate to="/creator-network" replace/>;
 if(!creator)return <main className="min-h-screen pt-36 text-center"><p className="text-red-600">{error}</p><button onClick={()=>void load()} className="mt-5 rounded-xl bg-primary px-5 py-3 font-bold text-white">Retry</button></main>;
 return <main className="min-h-screen bg-surface pt-24 md:pt-28">
  <section className="border-b bg-white py-5"><div className="mx-auto max-w-7xl px-6"><Link to="/creator-network" className="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-primary"><ArrowLeft size={16}/> Back to all creators</Link></div></section>
  <section className="bg-white py-12 md:py-16"><div className="mx-auto grid max-w-7xl gap-10 px-6 md:grid-cols-[minmax(280px,420px)_1fr] md:items-center lg:px-8">
   <div className="relative mx-auto aspect-[4/5] w-full max-w-sm overflow-hidden rounded-3xl bg-slate-100 shadow-xl md:mx-0"><img src={creator.profile_image_url||CREATOR_FALLBACK_IMAGE} alt={creator.display_name} onError={e=>{e.currentTarget.src=CREATOR_FALLBACK_IMAGE}} className="h-full w-full object-cover"/>{creator.is_verified&&<span className="absolute left-4 top-4 inline-flex items-center gap-1 rounded-full bg-white px-3 py-1.5 text-xs font-bold text-primary"><BadgeCheck size={15}/> Verified Creator</span>}</div>
   <div><div className="flex flex-wrap gap-2">{creator.categories.map(x=><span key={x} className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{x}</span>)}</div><h1 className="mt-5 font-heading text-4xl font-bold text-secondary md:text-5xl">{creator.display_name}</h1><p className="mt-3 flex items-center gap-2 text-sm text-gray-500"><MapPin size={16} className="text-primary"/>{creator.city||"Location not listed"}{creator.region?`, ${creator.region}`:""}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-gray-600">{creator.short_bio||"Creator profile"}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row">{safeUrl(creator.portfolio_url)&&<a href={creator.portfolio_url!} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-primary/25 bg-teal-50 px-6 py-3 text-sm font-bold text-primary">View Portfolio <ExternalLink size={15}/></a>}<button onClick={()=>setCollaborate(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-bold text-white hover:bg-primary-dark">Collaborate With Creator <ArrowRight size={16}/></button></div></div>
  </div></section>
  <section className="border-y border-gray-100 bg-white"><div className="mx-auto grid max-w-4xl grid-cols-3 px-6"><Metric icon={Users} value={formatCount(creator.followers)} label="Followers"/><Metric icon={BarChart3} value={`${creator.engagement_rate}%`} label="Engagement"/><Metric icon={MapPin} value={creator.city||"—"} label="City"/></div></section>
  <div className="mx-auto max-w-6xl space-y-10 px-6 py-16 lg:px-8">
   <Section title={`About ${creator.display_name}`}><p className="whitespace-pre-wrap leading-8 text-gray-600">{creator.about||"More information will be added soon."}</p></Section>
   <Section title="Social Media Presence"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{creator.socials.length?creator.socials.map((s,i)=><a key={`${s.profile_url}-${i}`} href={s.profile_url} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between rounded-2xl border border-primary/10 bg-white p-5 hover:border-primary hover:shadow"><span><strong className="block text-secondary">{s.platform}</strong><span className="text-xs text-gray-500">{s.handle||"View profile"}</span><span className="mt-2 block text-sm font-bold text-primary">{formatCount(s.follower_count)} followers</span>{s.follower_count_updated_at&&<span className="mt-1 block text-[10px] text-gray-400">Updated {new Date(s.follower_count_updated_at).toLocaleDateString()}</span>}</span><ExternalLink className="text-primary" size={18}/></a>):<Empty text="No social accounts listed."/>}</div></Section>
   <Section title="Content Expertise"><Tags values={creator.expertise}/></Section>
   <Section title="Featured Work"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{creator.featured_work.length?creator.featured_work.map((w,i)=><a key={`${w.work_url}-${i}`} href={w.work_url} target="_blank" rel="noopener noreferrer" className="group overflow-hidden rounded-2xl border border-gray-100 bg-white hover:shadow-lg"><img src={getCreatorWorkThumbnail(w)} alt={`${w.title} cover`} onError={e=>{e.currentTarget.src=CREATOR_FALLBACK_IMAGE}} className="h-44 w-full object-cover"/><div className="p-5"><span className="text-xs font-bold text-primary">{w.platform||"Featured work"}</span><h3 className="mt-1 flex items-center gap-2 font-bold text-secondary group-hover:text-primary">{w.title}<ExternalLink size={14}/></h3></div></a>):<Empty text="No featured work added yet."/>}</div></Section>
   <section className="grid gap-6 lg:grid-cols-[1fr_380px]"><div className="order-1 rounded-3xl bg-[#082f2a] p-7 text-white lg:order-2"><MessageCircle className="text-teal-300"/><h2 className="mt-4 font-heading text-2xl font-bold text-white">Collaborate with {creator.display_name}</h2><p className="mt-3 text-sm text-white/65">Send a Creator-specific campaign request directly through RaahX.</p><button onClick={()=>setCollaborate(true)} className="mt-6 w-full rounded-xl bg-primary px-5 py-3 font-bold text-white focus:ring-4 focus:ring-teal-300">Start Collaboration Proposal</button></div><div className="order-2 rounded-3xl border border-gray-100 bg-white p-7 lg:order-1"><h2 className="font-heading text-2xl font-bold"><span className="text-primary">/</span> Available For</h2><div className="mt-5">{creator.collaboration_types.length?<Tags values={creator.collaboration_types}/>:<Empty text="No collaboration types listed."/>}</div></div></section>
   {creator.brand_love_points.length>0&&<Section title={`Why Brands Love Working With ${creator.display_name}`}><div className="grid gap-5 sm:grid-cols-2">{creator.brand_love_points.map((p,i)=>{const Icon=creatorBrandIcon(p.icon_key);return <article key={i} className="rounded-2xl border border-primary/10 bg-teal-50/40 p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary text-white"><Icon size={21}/></span><h3 className="mt-4 font-heading text-lg font-bold">{p.heading}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{p.detail}</p></article>})}</div></Section>}
  </div>
  <section className="bg-primary px-6 py-14 text-center"><h2 className="font-heading text-3xl font-bold text-white">Have a project in mind?</h2><p className="mx-auto mt-3 max-w-xl text-white/75">Talk to the RaahX team and turn your next idea into measurable growth.</p><Link to="/proposal" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-primary">Talk to the RaahX Team <ArrowRight size={17}/></Link></section>
  {collaborate&&<CollaborationDialog creator={creator} onClose={()=>setCollaborate(false)}/>}</main>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-gray-100 bg-white p-6 md:p-9"><h2 className="mb-6 font-heading text-2xl font-bold text-secondary"><span className="mr-2 text-primary">/</span>{title}</h2>{children}</section>}
function Tags({values}:{values:string[]}){return <div className="flex flex-wrap gap-2">{values.length?values.map(x=><span key={x} className="rounded-full border border-primary/15 bg-teal-50 px-4 py-2 text-sm font-semibold text-primary">{x}</span>):<Empty text="Nothing listed yet."/>}</div>}
function Empty({text}:{text:string}){return <p className="text-sm text-gray-500">{text}</p>}
function Metric({icon:Icon,value,label}:{icon:typeof Users;value:string;label:string}){return <div className="border-r border-gray-100 py-6 text-center last:border-0"><Icon className="mx-auto text-primary" size={19}/><strong className="mt-2 block truncate text-lg">{value}</strong><span className="text-xs text-gray-500">{label}</span></div>}
function CollaborationDialog({creator,onClose}:{creator:CreatorRecord;onClose:()=>void}){const empty:CollaborationRequestInput={creator_id:creator.id,requester_name:"",company_name:null,email:"",whatsapp:null,campaign_type:null,campaign_budget:null,campaign_details:"",portfolio_url:null};const[form,setForm]=useState(empty);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(saving)return;setSaving(true);setError("");try{await submitCollaborationRequest(form);setSuccess(true)}catch(x){setError(creatorError(x))}finally{setSaving(false)}};const set=(key:keyof CollaborationRequestInput,v:string)=>setForm(x=>({...x,[key]:v||null}));return <div className="fixed inset-0 z-[90] overflow-y-auto bg-black/60 p-4"><div className="mx-auto my-8 max-w-2xl rounded-3xl bg-white p-6 md:p-8"><div className="flex justify-between"><h2 className="font-heading text-2xl font-bold">Collaborate with {creator.display_name}</h2><button onClick={onClose} aria-label="Close"><X/></button></div>{success?<div className="py-14 text-center"><BadgeCheck className="mx-auto text-primary" size={44}/><h3 className="mt-4 text-xl font-bold">Your collaboration request has been sent successfully.</h3></div>:<form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2">{[['Your Name *','requester_name'],['Company / Brand','company_name'],['Email Address *','email'],['WhatsApp Number','whatsapp'],['Campaign Type','campaign_type'],['Campaign Budget','campaign_budget'],['Portfolio / Work Link','portfolio_url']].map(([label,key])=><label key={key} className={`text-sm font-semibold ${key==='portfolio_url'?'sm:col-span-2':''}`}>{label}<input required={key==='requester_name'||key==='email'} type={key==='email'?'email':key==='portfolio_url'?'url':'text'} value={(form[key as keyof CollaborationRequestInput] as string)||""} onChange={e=>set(key as keyof CollaborationRequestInput,e.target.value)} className="mt-2 w-full rounded-xl border p-3 focus:border-primary focus:outline-none"/></label>)}<label className="sm:col-span-2 text-sm font-semibold">Campaign Details *<textarea required rows={5} value={form.campaign_details} onChange={e=>set('campaign_details',e.target.value)} className="mt-2 w-full rounded-xl border p-3 focus:border-primary focus:outline-none"/></label>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<button disabled={saving} className="sm:col-span-2 rounded-xl bg-primary py-3.5 font-bold text-white">{saving?"Sending...":"Send Collaboration Request"}</button></form>}</div></div>}
