-- Additive Services content model for the three approved source documents.
-- Review and run manually only after backing up the existing Services tables.
-- This migration preserves existing Service IDs and unrelated records.

SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='card_description'),'SELECT 1','ALTER TABLE services ADD COLUMN card_description TEXT NULL AFTER hero_subtitle'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='card_cta_label'),'SELECT 1','ALTER TABLE services ADD COLUMN card_cta_label VARCHAR(255) NULL AFTER card_description'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='hero_cta_label'),'SELECT 1','ALTER TABLE services ADD COLUMN hero_cta_label VARCHAR(255) NULL AFTER card_cta_label'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='overview_title'),'SELECT 1','ALTER TABLE services ADD COLUMN overview_title VARCHAR(500) NULL AFTER hero_cta_label'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='process_title'),'SELECT 1','ALTER TABLE services ADD COLUMN process_title VARCHAR(500) NULL AFTER why_choose_text'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='benefits_title'),'SELECT 1','ALTER TABLE services ADD COLUMN benefits_title VARCHAR(500) NULL AFTER process_title'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='cta_title'),'SELECT 1','ALTER TABLE services ADD COLUMN cta_title VARCHAR(500) NULL AFTER benefits_title'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='cta_text'),'SELECT 1','ALTER TABLE services ADD COLUMN cta_text TEXT NULL AFTER cta_title'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='cta_supporting_text'),'SELECT 1','ALTER TABLE services ADD COLUMN cta_supporting_text VARCHAR(1000) NULL AFTER cta_text'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = (SELECT IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='cta_label'),'SELECT 1','ALTER TABLE services ADD COLUMN cta_label VARCHAR(255) NULL AFTER cta_supporting_text'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS service_content_sections (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  service_id VARCHAR(191) NOT NULL,
  section_key VARCHAR(100) NOT NULL,
  eyebrow VARCHAR(255) NULL,
  heading VARCHAR(500) NOT NULL,
  body LONGTEXT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_service_content_section_key (service_id, section_key),
  KEY idx_service_content_sections_order (service_id, display_order),
  CONSTRAINT fk_service_content_sections_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_content_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  section_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  details TEXT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_service_content_item_order (section_id, display_order),
  CONSTRAINT fk_service_content_items_section FOREIGN KEY (section_id) REFERENCES service_content_sections (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Document-approved service card content and detail-page content.
UPDATE services SET name='Digital Marketing Services', card_description='Build a complete digital growth strategy that connects your marketing channels, audience, technology, and business goals.', card_cta_label='Explore Digital Marketing', hero_title='Digital Marketing Services That Actually Move the Needle', hero_subtitle='Turn your online presence into something that consistently brings in leads, customers, and revenue — not just traffic and vanity metrics.

At RaahX, we combine SEO, paid advertising, social media, content, and AI-driven insights into one connected strategy, so your business reaches the right people and converts more of them into paying customers.', hero_cta_label='Get Your Free Digital Marketing Proposal', overview_title='Turn Online Searches Into Real Business', overview='Somewhere right now, someone is searching for exactly what you sell. The question is whether they find your business first or a competitor''s.

That''s the gap the right digital marketing strategy closes.

Most agencies treat SEO, Google Ads, social media, and content as separate line items. We don''t. At RaahX, we connect them around one outcome: getting your business in front of the right audience and turning that attention into action.

We start by looking honestly at where you stand today — your website, your competitors, your market — and use that to figure out where the real opportunities are. From there, we build a strategy shaped by your budget, your audience, and what you''re actually trying to achieve.', why_choose_title='Why Businesses Choose RaahX', why_choose_text='Marketing Built Around Your Business, Not a Package

Plenty of agencies will promise you more traffic, more followers, more rankings. None of that means much if it''s not translating into revenue.

So before we pitch a channel or launch a single campaign, we take the time to actually understand your business, your customers, and your goals. The channels come after — not before.

A strategy shaped by your business
No template marketing plans copy-pasted between clients. Your industry, your competitors, your audience, and your sales process all shape what we recommend.

Reporting that actually makes sense
You shouldn''t need a marketing degree to read your own results. We report on what matters — leads, conversions, cost per acquisition, return on ad spend — not just clicks and impressions.

AI as a tool, not a replacement
We use AI to speed up research, spot opportunities, and make sense of campaign data faster. The strategic thinking behind your campaigns still comes from our team.

Channels that talk to each other
Your Google Ads data can point to search trends worth chasing in SEO. Your SEO performance can surface content ideas. Your social audience can sharpen your paid targeting. We use what one channel tells us to improve the others.

Ongoing improvement, not a set-and-forget campaign
We keep watching performance, testing what could work better, and adjusting when the numbers point somewhere new.', process_title='How We Make It Happen', benefits_title='What You Actually Get With RaahX', cta_title='Ready to Build Smarter and Grow Faster?', cta_text='Partner with a digital marketing agency that combines strategy, creativity, technology, data, and AI to turn your online presence into a scalable growth engine.', cta_supporting_text='Tell us where your business is today, where you want to go, and we''ll help map the path forward.', cta_label='Get Your Free Digital Marketing Proposal' WHERE slug='digital-marketing';
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Projects Delivered', child.value='150+' WHERE service.slug='digital-marketing' AND child.display_order=0;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Projects Delivered', '150+', 0 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Client Rating', child.value='4.9★' WHERE service.slug='digital-marketing' AND child.display_order=1;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Client Rating', '4.9★', 1 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Average ROI Increase', child.value='3x' WHERE service.slug='digital-marketing' AND child.display_order=2;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Average ROI Increase', '3x', 2 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Discovery & Marketing Audit', child.description='We start by getting to know your business — your website, current marketing, competitors, audience, and results. Includes: business research, audience research, competitor analysis, website review, channel audit, conversion review, and growth opportunities.' WHERE service.slug='digital-marketing' AND child.display_order=0;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Discovery & Marketing Audit', 'We start by getting to know your business — your website, current marketing, competitors, audience, and results. Includes: business research, audience research, competitor analysis, website review, channel audit, conversion review, and growth opportunities.', 0 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Digital Marketing Strategy', child.description='We choose channels and priorities based on your goals, budget, audience, and sales cycle. Includes: marketing strategy, channel planning, audience targeting, customer journey, campaign planning, budget planning, and KPI setting.' WHERE service.slug='digital-marketing' AND child.display_order=1;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Digital Marketing Strategy', 'We choose channels and priorities based on your goals, budget, audience, and sales cycle. Includes: marketing strategy, channel planning, audience targeting, customer journey, campaign planning, budget planning, and KPI setting.', 1 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Integrated Campaign Execution', child.description='We manage the channels your business needs under one connected strategy. Includes: SEO, PPC and Google Ads, social media, content marketing, paid social, landing-page optimization, and performance marketing.' WHERE service.slug='digital-marketing' AND child.display_order=2;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Integrated Campaign Execution', 'We manage the channels your business needs under one connected strategy. Includes: SEO, PPC and Google Ads, social media, content marketing, paid social, landing-page optimization, and performance marketing.', 2 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Data-Driven Optimization', child.description='We review what drives results and adjust what does not. Includes: performance tracking, conversion analysis, A/B testing, audience refinement, ad optimization, budget adjustments, and ROI analysis.' WHERE service.slug='digital-marketing' AND child.display_order=3;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Data-Driven Optimization', 'We review what drives results and adjust what does not. Includes: performance tracking, conversion analysis, A/B testing, audience refinement, ad optimization, budget adjustments, and ROI analysis.', 3 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=3);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='More Qualified Traffic', child.description='We focus on reaching people who actually want what you offer, not chasing numbers for their own sake.' WHERE service.slug='digital-marketing' AND child.display_order=0;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'More Qualified Traffic', 'We focus on reaching people who actually want what you offer, not chasing numbers for their own sake.', 0 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='More Opportunities to Convert', child.description='We improve the path from the first click to the enquiry, booking, or purchase.' WHERE service.slug='digital-marketing' AND child.display_order=1;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'More Opportunities to Convert', 'We improve the path from the first click to the enquiry, booking, or purchase.', 1 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Better Decisions, Backed by Data', child.description='Real campaign data and customer behaviour guide our recommendations, not guesswork.' WHERE service.slug='digital-marketing' AND child.display_order=2;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Better Decisions, Backed by Data', 'Real campaign data and customer behaviour guide our recommendations, not guesswork.', 2 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='A Stronger, More Consistent Presence', child.description='We keep your brand visible and recognizable whether customers find you on Google or social media.' WHERE service.slug='digital-marketing' AND child.display_order=3;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'A Stronger, More Consistent Presence', 'We keep your brand visible and recognizable whether customers find you on Google or social media.', 3 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=3);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Growth That Compounds', child.description='The goal is not one good campaign. It is finding what works and building on it as your business grows.' WHERE service.slug='digital-marketing' AND child.display_order=4;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Growth That Compounds', 'The goal is not one good campaign. It is finding what works and building on it as your business grows.', 4 FROM services service WHERE service.slug='digital-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=4);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'full-process', NULL, 'Our Process, Step by Step', NULL, 0 FROM services WHERE slug='digital-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Discover', 'We learn your business, your customers, your competitors, and your goals.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Audit', 'We review your website, SEO, ads, content, social, and conversion performance to find the gaps.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Strategize', 'We turn what we find into a clear roadmap with real priorities and measurable goals.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Execute', 'We launch and manage the right campaigns, keeping every channel connected.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Optimize', 'We monitor results, test new approaches, and refine based on the data.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Scale', 'When something works, we expand it through more budget, audiences, and channels.', NULL, 5 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='full-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'service-types', NULL, 'Our Digital Marketing Services', NULL, 1 FROM services WHERE slug='digital-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'SEO Services', 'Get found when people are actively searching through technical SEO, keyword research, content optimization, internal linking, and authority building.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'PPC Services', 'Reach people ready to act through Google Ads and paid search, with continual keyword, copy, targeting, and budget refinement.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Social Media Marketing', 'Stay relevant through content and engagement strategies built around awareness and bringing people back to your business.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Content Marketing', 'Articles, landing pages, and content that answer customer questions, support SEO, and move people closer to a decision.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Performance Marketing', 'Measure every dollar against real outcomes and continually refine what is not generating returns.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'business-growth', NULL, 'Will Digital Marketing Actually Grow My Business?', 'Honestly — that''s the right question to ask. Better rankings, traffic, and followers are useful only when they lead to enquiries, customers, or revenue. At RaahX, traffic, rankings, and engagement are steps toward something bigger: more of the right people finding you, more of them taking action, and more of them choosing your business over the competition.', 2 FROM services WHERE slug='digital-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'faqs', 'Frequently Asked Questions', 'Digital Marketing Questions, Answered', NULL, 3 FROM services WHERE slug='digital-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'How is RaahX different from other digital marketing companies in Pakistan?', 'We identify which channels are worth investing in based on your audience, competitors, goals, and budget, then run them together instead of as disconnected campaigns.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'How soon can I expect results?', 'It depends on the channel. Paid advertising can produce data and leads quickly, while SEO and content marketing take longer because organic visibility and authority build over time.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Do you work with businesses outside Pakistan?', 'Yes. We work locally across Pakistan and in international markets. The strategy depends on where your customers are and how they buy.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'What does AI-powered digital marketing actually mean here?', 'We use AI for audience research, data analysis, content research, and spotting opportunities faster, while strategic decisions remain with our team.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Can you manage all our digital marketing channels?', 'Yes. SEO, PPC, social, content, and performance campaigns can run under one strategy, or we can focus on only the channels you need.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='digital-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
UPDATE services SET name='Social Media Marketing', card_description='Build an active social presence with strategic content, audience engagement, paid campaigns, and performance-focused social media marketing.', card_cta_label='Explore Social Media', hero_title='Build a Stronger Brand Through Strategic Social Media', hero_subtitle='Turn scrolling audiences into loyal customers with social media marketing built to increase visibility, engagement, and qualified leads — not just likes.', hero_cta_label='', overview_title='Social Media That Does More Than Fill Your Feed', overview='Turn Attention Into Meaningful Action

Your customers are already spending hours a day on social media. The hard part isn''t finding them — it''s earning their attention and giving them a reason to engage with your brand.

RaahX brings together social strategy, creative content, audience engagement, paid campaigns, and performance analytics to help businesses build real online communities and turn those interactions into business opportunities.

Posting consistently isn''t the goal on its own. We build data-driven social strategies that connect your brand with potential customers, build credibility, spark engagement, and support your broader marketing goals.', why_choose_title='What Our Social Media Marketing Can Do for Your Brand', why_choose_text='A Strategy Built Around Your Business

Every campaign has a clear job to do — whether that is raising awareness or generating qualified leads. Strategy comes before content, creative works alongside data, engagement builds relationships, and clear analytics show what is working.', process_title='Our Social Media Marketing Process', benefits_title='More Than Followers. More Meaningful Growth.', cta_title='Ready to Turn Social Media Into a Growth Channel?', cta_text='Your audience is already on social media. Let''s give them a reason to notice, trust, and choose your brand.', cta_supporting_text='Get a customized, data-driven social media roadmap built around your goals.', cta_label='Get Your Free Proposal' WHERE slug='social-media-marketing';
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Campaigns Managed', child.value='200+' WHERE service.slug='social-media-marketing' AND child.display_order=0;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Campaigns Managed', '200+', 0 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Average Engagement Lift', child.value='45%' WHERE service.slug='social-media-marketing' AND child.display_order=1;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Average Engagement Lift', '45%', 1 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Client Rating', child.value='4.8★' WHERE service.slug='social-media-marketing' AND child.display_order=2;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Client Rating', '4.8★', 2 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Understand Your Audience', child.description='We identify who you want to reach, including their interests, behaviors, needs, and preferred platforms.' WHERE service.slug='social-media-marketing' AND child.display_order=0;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Understand Your Audience', 'We identify who you want to reach, including their interests, behaviors, needs, and preferred platforms.', 0 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Build Your Strategy', child.description='We shape a strategy around your business goals, customer journey, brand positioning, and growth opportunities.' WHERE service.slug='social-media-marketing' AND child.display_order=1;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Build Your Strategy', 'We shape a strategy around your business goals, customer journey, brand positioning, and growth opportunities.', 1 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Create Content That Connects', child.description='We develop content that reflects your brand and gives your audience real reasons to engage.' WHERE service.slug='social-media-marketing' AND child.display_order=2;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Create Content That Connects', 'We develop content that reflects your brand and gives your audience real reasons to engage.', 2 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Launch & Manage Campaigns', child.description='We publish, monitor, and manage campaigns while engaging your audience and maintaining consistent communication.' WHERE service.slug='social-media-marketing' AND child.display_order=3;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Launch & Manage Campaigns', 'We publish, monitor, and manage campaigns while engaging your audience and maintaining consistent communication.', 3 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=3);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Measure What Matters', child.description='We track engagement, reach, audience growth, traffic, leads, and overall campaign performance.' WHERE service.slug='social-media-marketing' AND child.display_order=4;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Measure What Matters', 'We track engagement, reach, audience growth, traffic, leads, and overall campaign performance.', 4 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=4);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Optimize for Better Results', child.description='We use performance data to fix what is underperforming and build on what works.' WHERE service.slug='social-media-marketing' AND child.display_order=5;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Optimize for Better Results', 'We use performance data to fix what is underperforming and build on what works.', 5 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=5);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Stronger Brand Loyalty', child.description='Consistent communication and useful content build lasting audience relationships.' WHERE service.slug='social-media-marketing' AND child.display_order=0;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Stronger Brand Loyalty', 'Consistent communication and useful content build lasting audience relationships.', 0 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='More Engagement', child.description='Give people something worth responding to, sharing, saving, or discussing.' WHERE service.slug='social-media-marketing' AND child.display_order=1;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'More Engagement', 'Give people something worth responding to, sharing, saving, or discussing.', 1 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Better Quality Leads', child.description='Turn social attention into opportunities through strategic content, clear calls to action, and targeted campaigns.' WHERE service.slug='social-media-marketing' AND child.display_order=2;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Better Quality Leads', 'Turn social attention into opportunities through strategic content, clear calls to action, and targeted campaigns.', 2 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='A Stronger Online Presence', child.description='Stay visible and recognizable throughout the customer journey, not just in a single post.' WHERE service.slug='social-media-marketing' AND child.display_order=3;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'A Stronger Online Presence', 'Stay visible and recognizable throughout the customer journey, not just in a single post.', 3 FROM services service WHERE service.slug='social-media-marketing' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=3);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'capabilities', NULL, 'Content and Campaigns Built to Perform', NULL, 0 FROM services WHERE slug='social-media-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Content Worth Stopping For', 'We combine strong copy, branded visuals, educational posts, promotions, short-form video, and storytelling.', 'Build brand awareness
Educate potential customers
Showcase products or services
Spark genuine engagement
Build trust and credibility
Drive website traffic
Generate leads', 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='capabilities' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Campaigns Managed From Idea to Result', 'We plan, execute, and continually adjust campaigns while monitoring targeting, creative performance, engagement, traffic, and conversions.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='capabilities' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Paid Social to Reach the Right People, Faster', 'We run paid campaigns for awareness, traffic, lead generation, promotion, acquisition, retargeting, sales, and conversions.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='capabilities' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'growth-stages', NULL, 'Social Media Marketing for Every Stage of Growth', NULL, 1 FROM services WHERE slug='social-media-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'For Businesses', 'Align social activity with broader goals, from awareness to qualified leads.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='growth-stages' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'For Small Businesses', 'Build credibility, reach local audiences, and compete effectively with a focused strategy and budget.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='growth-stages' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'For Startups', 'Introduce your brand, communicate what makes it different, and build a community from day one.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='growth-stages' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'For Established Brands', 'Strengthen recognition through consistent messaging, storytelling, and a presence that reflects the brand.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='growth-stages' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'For eCommerce', 'Showcase products, engage buyers, drive targeted traffic, and support organic and paid sales.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='growth-stages' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'social-difference', NULL, 'Why Businesses Choose RaahX for Social Media', NULL, 2 FROM services WHERE slug='social-media-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Strategy Comes Before Content', 'Every campaign starts with your audience, objective, and desired outcome.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='social-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Creative Meets Data', 'Engaging content paired with performance insight allows the strategy to evolve.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='social-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Engagement That Builds Relationships', 'We focus on interactions that build trust and keep people coming back.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='social-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Results You Can Actually Measure', 'Clear analytics show what works and how your investment contributes to growth.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='social-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'social-goals', NULL, 'Your Social Media, Working Toward Real Business Goals', 'Social media should do more than collect likes and followers. When strategy, content, community management, paid social, and analytics work together, social channels become a genuine part of customer acquisition and growth.', 3 FROM services WHERE slug='social-media-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'faqs', 'Frequently Asked Questions', 'Social Media Marketing Questions, Answered', NULL, 4 FROM services WHERE slug='social-media-marketing' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Which social media platforms should my business actually be on?', 'It depends on where your customers spend time, not which platform is trending. A B2B company may gain more from LinkedIn while an eCommerce brand may gain more from Instagram.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'How long does it take to see results from social media marketing?', 'Paid social can generate traffic and leads within days. Organic growth, engagement, and community trust usually build over several months.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Do you handle both organic content and paid advertising?', 'Yes. We manage organic content, community engagement, and paid campaigns together under the same strategy.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Will I have input on the content before it goes live?', 'Yes. We share content calendars and creative for review so you can provide input on tone, messaging, and timing.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'How do you measure whether a campaign is actually working?', 'We look beyond likes and followers to engagement rate, website traffic, lead generation, and conversions tied to business goals.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='social-media-marketing' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
UPDATE services SET name='SEO Services', card_description='Increase organic visibility, attract high-intent traffic, improve search rankings, and generate sustainable growth with research-driven SEO strategies.', card_cta_label='Explore SEO Services', hero_title='Increase Organic Traffic and Build Long-Term Business Growth', hero_subtitle='Get found by the right customers when they search for your products or services. Our data-driven SEO strategies improve search visibility, attract qualified traffic, and turn organic visitors into customers.', hero_cta_label='Get Your Free SEO Proposal', overview_title='Turn Google Searches Into Real Business Growth', overview='Your customers are already searching for the products and services you offer. Our SEO services help your business appear in front of them at the exact moment they are ready to take action.

From technical SEO and keyword research to content optimization, local SEO, and authority building, we create a complete search strategy designed around your business goals — not just rankings.', why_choose_title='Why Choose Our SEO Services?', why_choose_text='Search engines are constantly changing, but the fundamentals remain the same: a technically strong website, valuable content, relevant keywords, strong authority, and an excellent user experience.

We combine these elements into one strategic SEO campaign designed to increase organic visibility, attract qualified visitors, and generate sustainable business growth.

No shortcuts. No keyword stuffing. No dependence on paid advertising. Just a structured SEO strategy built for long-term results.', process_title='How We Make It Happen', benefits_title='Your Unfair Advantage', testimonial_quote='Our website rankings improved significantly, and we now receive consistent organic leads every month. The ROI has been incredible.', testimonial_author='Muhammad Ali', cta_title='Turn Search Traffic Into Business Growth', cta_text='Get a customized, data-driven SEO strategy tailored specifically to your business, market, and growth goals.', cta_supporting_text='Free consultation • Customized strategy • No obligation', cta_label='Get Your Free SEO Proposal' WHERE slug='seo-services';
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Keywords Ranked', child.value='500+' WHERE service.slug='seo-services' AND child.display_order=0;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Keywords Ranked', '500+', 0 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Average Traffic Growth', child.value='124%' WHERE service.slug='seo-services' AND child.display_order=1;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Average Traffic Growth', '124%', 1 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_stats child JOIN services service ON service.id=child.service_id SET child.label='Client Rating', child.value='4.9★' WHERE service.slug='seo-services' AND child.display_order=2;
INSERT INTO service_stats (service_id, label, value, display_order) SELECT service.id, 'Client Rating', '4.9★', 2 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_stats existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Technical SEO Audit', child.description='We identify and fix issues that prevent crawling, understanding, and indexing. Includes: crawling and indexing, site architecture, Core Web Vitals, mobile usability, canonicals, redirects, schema, and XML sitemaps.' WHERE service.slug='seo-services' AND child.display_order=0;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Technical SEO Audit', 'We identify and fix issues that prevent crawling, understanding, and indexing. Includes: crawling and indexing, site architecture, Core Web Vitals, mobile usability, canonicals, redirects, schema, and XML sitemaps.', 0 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Keyword & Competitor Research', child.description='We find customer search terms and analyze competitors. Includes: keyword research, search intent, competitor analysis, keyword gaps, SERP analysis, and commercial opportunities.' WHERE service.slug='seo-services' AND child.display_order=1;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Keyword & Competitor Research', 'We find customer search terms and analyze competitors. Includes: keyword research, search intent, competitor analysis, keyword gaps, SERP analysis, and commercial opportunities.', 1 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='On-Page & Content Optimization', child.description='We optimize pages and build a content strategy. Includes: title tags, meta descriptions, headings, content optimization, internal linking, semantic keywords, and search-intent optimization.' WHERE service.slug='seo-services' AND child.display_order=2;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'On-Page & Content Optimization', 'We optimize pages and build a content strategy. Includes: title tags, meta descriptions, headings, content optimization, internal linking, semantic keywords, and search-intent optimization.', 2 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=2);
UPDATE service_process_steps child JOIN services service ON service.id=child.service_id SET child.title='Authority Building', child.description='We strengthen authority using link opportunities, digital PR, relevant backlinks, brand mentions, local citations, and sustainable authority development.' WHERE service.slug='seo-services' AND child.display_order=3;
INSERT INTO service_process_steps (service_id, title, description, display_order) SELECT service.id, 'Authority Building', 'We strengthen authority using link opportunities, digital PR, relevant backlinks, brand mentions, local citations, and sustainable authority development.', 3 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_process_steps existing WHERE existing.service_id=service.id AND existing.display_order=3);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Sustainable Traffic', child.description='Build a consistent stream of qualified organic visitors without relying entirely on paid advertising.' WHERE service.slug='seo-services' AND child.display_order=0;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Sustainable Traffic', 'Build a consistent stream of qualified organic visitors without relying entirely on paid advertising.', 0 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=0);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Higher Conversion Rates', child.description='Target users with strong search intent and connect them with pages designed to convert.' WHERE service.slug='seo-services' AND child.display_order=1;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Higher Conversion Rates', 'Target users with strong search intent and connect them with pages designed to convert.', 1 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=1);
UPDATE service_benefits child JOIN services service ON service.id=child.service_id SET child.title='Industry Authority', child.description='Build a trusted resource recognized by search engines and customers in your market.' WHERE service.slug='seo-services' AND child.display_order=2;
INSERT INTO service_benefits (service_id, title, description, display_order) SELECT service.id, 'Industry Authority', 'Build a trusted resource recognized by search engines and customers in your market.', 2 FROM services service WHERE service.slug='seo-services' AND NOT EXISTS (SELECT 1 FROM service_benefits existing WHERE existing.service_id=service.id AND existing.display_order=2);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'seo-process', NULL, 'Our SEO Process', NULL, 0 FROM services WHERE slug='seo-services' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Discover', 'We learn about your business, customers, competitors, goals, and current search visibility.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Audit', 'We analyze technical health, content, keywords, backlinks, and overall SEO performance.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Strategize', 'We build a prioritized SEO roadmap around the opportunities with the greatest business impact.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Optimize', 'We improve site structure, pages, content, internal links, technical SEO, and conversion elements.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Grow', 'We monitor rankings, traffic, conversions, competitors, and new search opportunities.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Scale', 'We expand into new keywords, topics, locations, services, and revenue opportunities.', NULL, 5 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-process' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'seo-service-types', NULL, 'SEO Services We Provide', NULL, 1 FROM services WHERE slug='seo-services' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Technical SEO', 'Fix technical problems affecting crawling, indexing, performance, and search visibility.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'On-Page SEO', 'Optimize pages for relevant keywords, search intent, users, and search engines.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Keyword Research', 'Find profitable keywords based on volume, competition, intent, and business value.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Content SEO', 'Create and optimize helpful content that satisfies users and builds topical authority.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Local SEO', 'Improve location-based visibility and help nearby customers find your business.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Ecommerce SEO', 'Optimize product, category, collection, and supporting pages for organic ecommerce traffic.', NULL, 5 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Link Building', 'Build relevant authority through outreach, digital PR, partnerships, and quality link opportunities.', NULL, 6 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'SEO Audits', 'Analyze technical, on-page, content, off-page, and competitive SEO opportunities.', NULL, 7 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-service-types' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'business-goals', NULL, 'Built Around Your Business Goals', NULL, 2 FROM services WHERE slug='seo-services' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'More Visibility', 'Reach more people searching for what you offer.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='business-goals' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'More Qualified Traffic', 'Attract visitors with genuine interest and buying intent.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='business-goals' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'More Leads', 'Turn organic traffic into calls, forms, bookings, and enquiries.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='business-goals' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'More Revenue', 'Build an SEO channel that contributes to sustainable business growth.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='business-goals' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'seo-difference', NULL, 'What Makes Our SEO Different?', NULL, 3 FROM services WHERE slug='seo-services' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Strategy Before Execution', 'Every action starts with research and a clear objective rather than blind page optimization.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Data-Driven Decisions', 'Search data, competitor insights, analytics, and ranking trends determine priorities.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Search Intent First', 'We focus on why someone searches, not rankings that do not match your business.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Technical + Content + Authority', 'We work across the entire search ecosystem because successful SEO requires more than content.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Transparent Reporting', 'You can see what we are working on, what changed, and how organic performance is developing.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='seo-difference' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_sections (service_id, section_key, eyebrow, heading, body, display_order) SELECT id, 'faqs', 'Frequently Asked Questions', 'SEO Questions, Answered', NULL, 4 FROM services WHERE slug='seo-services' ON DUPLICATE KEY UPDATE eyebrow=VALUES(eyebrow), heading=VALUES(heading), body=VALUES(body), display_order=VALUES(display_order);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'How long does SEO take to show results?', 'Some improvements appear within the first few months, while competitive keywords and industries require more time and consistent optimization.', NULL, 0 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'What does an SEO campaign include?', 'Technical SEO, keyword and competitor research, on-page optimization, content strategy, internal linking, local SEO, authority building, and ongoing monitoring.', NULL, 1 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Can you improve my existing website''s rankings?', 'Yes. We audit existing websites, identify barriers and missed opportunities, and create a prioritized optimization plan.', NULL, 2 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Do you guarantee first-page Google rankings?', 'No reputable provider can guarantee a specific position. We improve the factors that influence visibility and build sustainable search growth.', NULL, 3 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Will SEO increase my leads and sales?', 'SEO attracts relevant users actively searching for your offer, while results also depend on the offer, website experience, competition, and conversion process.', NULL, 4 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
INSERT INTO service_content_items (section_id, title, description, details, display_order) SELECT section.id, 'Do you provide local SEO?', 'Yes. Local SEO improves location-based visibility and can generate nearby calls, enquiries, and visits.', NULL, 5 FROM service_content_sections section JOIN services service ON service.id=section.service_id WHERE service.slug='seo-services' AND section.section_key='faqs' ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description), details=VALUES(details);
UPDATE services SET name='Website Development', card_description='Create fast, responsive, SEO-friendly websites designed to build trust, improve user experience, and turn visitors into customers.', card_cta_label='Explore Web Development' WHERE slug='website-development';
UPDATE services SET name='Branding Services', card_description='Create a memorable brand identity with strategic positioning, visual identity, messaging, and creative assets built around your audience.', card_cta_label='Explore Branding' WHERE slug='branding';
UPDATE services SET name='Meta Advertising', card_description='Reach the right audience and generate measurable results through strategically planned Meta advertising campaigns optimized for conversions and growth.', card_cta_label='Explore Meta Ads' WHERE slug='meta-advertising';
UPDATE services SET name='AI Automation Services', card_description='Automate repetitive workflows, improve efficiency, and create smarter business processes using practical AI and marketing automation solutions.', card_cta_label='Explore AI Automation' WHERE slug='ai-automation';
UPDATE services SET name='Graphic Design Services', card_description='Create professional, conversion-focused visuals that strengthen your brand across websites, social media, advertising, and digital campaigns.', card_cta_label='Explore Graphic Design' WHERE slug='graphic-design';
UPDATE services SET name='Business Strategy & Growth Consulting', card_description='Turn business goals into actionable growth plans with market research, competitive analysis, strategic planning, and performance insights.', card_cta_label='Explore Growth Consulting' WHERE slug='business-strategy';
UPDATE services SET name='App Development', card_description='Build scalable, user-friendly applications that support your digital ecosystem, customer experience, and long-term business growth.', card_cta_label='Explore App Development' WHERE slug='app-development';
